# Este archivo configura el servidor de Railway (Nixpacks)
# Instala las dependencias de sistema necesarias como ffmpeg y python

[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run app.py"
