[theme]
base = "light"

# TU PALETA NÓRDICA (Extraída de la imagen)

# Color Principal (Botones, Acentos, Deslizadores)
# Usamos el Azul Pizarra (#5B687C) para un look profesional y calmado.
primaryColor = "#5B687C"

# Fondo Principal
# Blanco puro para limpieza máxima.
backgroundColor = "#FFFFFF"

# Fondo Secundario (Barra lateral, inputs)
# Usamos el tono "Mushroom/Beige" muy suave (#F4F7F6) para dar calidez sin ensuciar.
secondaryBackgroundColor = "#F4F7F6"

# Color del Texto
# El Azul Navy Oscuro (#161B2F) para lectura perfecta y alto contraste.
textColor = "#161B2F"

# Tipografía Moderna
font = "sans serif"

[server]
runOnSave = true
headless = true
